### ISSUE TITLE
This is bad design.

### ISSUE THREAD

**Issue by pjohri1992** [ajohri/InterviewPrep#2]
https://github.com/ajohri/InterviewPrep/blob/5aa1f6b02a0038fcf36bba53e1efb0f76e1ada11/InterviewPrep/src/LinkedList/Node.java#L7

Now when you make an instance of Node it gets set to zero and you have to have a separate call for setting the value and next pointer. 

Do your Design with just one constructor:

public Node(int n) {
    this.num = n;
    this.next = null;
}

Then in cases when you have just have to make one node you that node setup.

**Comment by ajohri** [comment]
This is corrected.
